// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: deduction/deduction.proto

package deductionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeductionService_SolveCase_FullMethodName = "/deductionpb.DeductionService/SolveCase"
)

// DeductionServiceClient is the client API for DeductionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeductionServiceClient interface {
	SolveCase(ctx context.Context, in *SolveCaseRequest, opts ...grpc.CallOption) (*CaseSolution, error)
}

type deductionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeductionServiceClient(cc grpc.ClientConnInterface) DeductionServiceClient {
	return &deductionServiceClient{cc}
}

func (c *deductionServiceClient) SolveCase(ctx context.Context, in *SolveCaseRequest, opts ...grpc.CallOption) (*CaseSolution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaseSolution)
	err := c.cc.Invoke(ctx, DeductionService_SolveCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeductionServiceServer is the server API for DeductionService service.
// All implementations must embed UnimplementedDeductionServiceServer
// for forward compatibility.
type DeductionServiceServer interface {
	SolveCase(context.Context, *SolveCaseRequest) (*CaseSolution, error)
	mustEmbedUnimplementedDeductionServiceServer()
}

// UnimplementedDeductionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeductionServiceServer struct{}

func (UnimplementedDeductionServiceServer) SolveCase(context.Context, *SolveCaseRequest) (*CaseSolution, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolveCase not implemented")
}
func (UnimplementedDeductionServiceServer) mustEmbedUnimplementedDeductionServiceServer() {}
func (UnimplementedDeductionServiceServer) testEmbeddedByValue()                          {}

// UnsafeDeductionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeductionServiceServer will
// result in compilation errors.
type UnsafeDeductionServiceServer interface {
	mustEmbedUnimplementedDeductionServiceServer()
}

func RegisterDeductionServiceServer(s grpc.ServiceRegistrar, srv DeductionServiceServer) {
	// If the following call pancis, it indicates UnimplementedDeductionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeductionService_ServiceDesc, srv)
}

func _DeductionService_SolveCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolveCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeductionServiceServer).SolveCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeductionService_SolveCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeductionServiceServer).SolveCase(ctx, req.(*SolveCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeductionService_ServiceDesc is the grpc.ServiceDesc for DeductionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeductionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deductionpb.DeductionService",
	HandlerType: (*DeductionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SolveCase",
			Handler:    _DeductionService_SolveCase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deduction/deduction.proto",
}
