// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: crimelab.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeEvidenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EvidenceId string `protobuf:"bytes,1,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
}

func (x *AnalyzeEvidenceRequest) Reset() {
	*x = AnalyzeEvidenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_crimelab_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyzeEvidenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeEvidenceRequest) ProtoMessage() {}

func (x *AnalyzeEvidenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crimelab_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeEvidenceRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeEvidenceRequest) Descriptor() ([]byte, []int) {
	return file_crimelab_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeEvidenceRequest) GetEvidenceId() string {
	if x != nil {
		return x.EvidenceId
	}
	return ""
}

type AnalysisResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EvidenceId   string `protobuf:"bytes,1,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	MinigameType string `protobuf:"bytes,2,opt,name=minigame_type,json=minigameType,proto3" json:"minigame_type,omitempty"`
	MinigameData string `protobuf:"bytes,3,opt,name=minigame_data,json=minigameData,proto3" json:"minigame_data,omitempty"`
	Result       string `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AnalysisResult) Reset() {
	*x = AnalysisResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_crimelab_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResult) ProtoMessage() {}

func (x *AnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_crimelab_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResult.ProtoReflect.Descriptor instead.
func (*AnalysisResult) Descriptor() ([]byte, []int) {
	return file_crimelab_proto_rawDescGZIP(), []int{1}
}

func (x *AnalysisResult) GetEvidenceId() string {
	if x != nil {
		return x.EvidenceId
	}
	return ""
}

func (x *AnalysisResult) GetMinigameType() string {
	if x != nil {
		return x.MinigameType
	}
	return ""
}

func (x *AnalysisResult) GetMinigameData() string {
	if x != nil {
		return x.MinigameData
	}
	return ""
}

func (x *AnalysisResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_crimelab_proto protoreflect.FileDescriptor

var file_crimelab_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x72, 0x69, 0x6d, 0x65, 0x6c, 0x61, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x63, 0x72, 0x69, 0x6d, 0x65, 0x6c, 0x61, 0x62, 0x22, 0x39, 0x0a, 0x16, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x7a, 0x65, 0x45, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x76, 0x69, 0x64, 0x65,
	0x6e, 0x63, 0x65, 0x49, 0x64, 0x22, 0x93, 0x01, 0x0a, 0x0e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73,
	0x69, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x76, 0x69, 0x64,
	0x65, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65,
	0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x69, 0x6e,
	0x69, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x62, 0x0a, 0x0f, 0x43,
	0x72, 0x69, 0x6d, 0x65, 0x4c, 0x61, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f,
	0x0a, 0x0f, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x45, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63,
	0x65, 0x12, 0x20, 0x2e, 0x63, 0x72, 0x69, 0x6d, 0x65, 0x6c, 0x61, 0x62, 0x2e, 0x41, 0x6e, 0x61,
	0x6c, 0x79, 0x7a, 0x65, 0x45, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x63, 0x72, 0x69, 0x6d, 0x65, 0x6c, 0x61, 0x62, 0x2e, 0x41,
	0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42,
	0x0f, 0x5a, 0x0d, 0x6f, 0x64, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_crimelab_proto_rawDescOnce sync.Once
	file_crimelab_proto_rawDescData = file_crimelab_proto_rawDesc
)

func file_crimelab_proto_rawDescGZIP() []byte {
	file_crimelab_proto_rawDescOnce.Do(func() {
		file_crimelab_proto_rawDescData = protoimpl.X.CompressGZIP(file_crimelab_proto_rawDescData)
	})
	return file_crimelab_proto_rawDescData
}

var file_crimelab_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_crimelab_proto_goTypes = []any{
	(*AnalyzeEvidenceRequest)(nil), // 0: crimelab.AnalyzeEvidenceRequest
	(*AnalysisResult)(nil),         // 1: crimelab.AnalysisResult
}
var file_crimelab_proto_depIdxs = []int32{
	0, // 0: crimelab.CrimeLabService.AnalyzeEvidence:input_type -> crimelab.AnalyzeEvidenceRequest
	1, // 1: crimelab.CrimeLabService.AnalyzeEvidence:output_type -> crimelab.AnalysisResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_crimelab_proto_init() }
func file_crimelab_proto_init() {
	if File_crimelab_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_crimelab_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AnalyzeEvidenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_crimelab_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AnalysisResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_crimelab_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crimelab_proto_goTypes,
		DependencyIndexes: file_crimelab_proto_depIdxs,
		MessageInfos:      file_crimelab_proto_msgTypes,
	}.Build()
	File_crimelab_proto = out.File
	file_crimelab_proto_rawDesc = nil
	file_crimelab_proto_goTypes = nil
	file_crimelab_proto_depIdxs = nil
}
