// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: interrogation/interrogation.proto

package interrogationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WitnessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationId string `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
}

func (x *WitnessRequest) Reset() {
	*x = WitnessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interrogation_interrogation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WitnessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WitnessRequest) ProtoMessage() {}

func (x *WitnessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interrogation_interrogation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WitnessRequest.ProtoReflect.Descriptor instead.
func (*WitnessRequest) Descriptor() ([]byte, []int) {
	return file_interrogation_interrogation_proto_rawDescGZIP(), []int{0}
}

func (x *WitnessRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

type WitnessStatement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Statement string `protobuf:"bytes,1,opt,name=statement,proto3" json:"statement,omitempty"`
}

func (x *WitnessStatement) Reset() {
	*x = WitnessStatement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interrogation_interrogation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WitnessStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WitnessStatement) ProtoMessage() {}

func (x *WitnessStatement) ProtoReflect() protoreflect.Message {
	mi := &file_interrogation_interrogation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WitnessStatement.ProtoReflect.Descriptor instead.
func (*WitnessStatement) Descriptor() ([]byte, []int) {
	return file_interrogation_interrogation_proto_rawDescGZIP(), []int{1}
}

func (x *WitnessStatement) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

type InterrogationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuspectId  string `protobuf:"bytes,1,opt,name=suspect_id,json=suspectId,proto3" json:"suspect_id,omitempty"`
	QuestionId string `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
}

func (x *InterrogationRequest) Reset() {
	*x = InterrogationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interrogation_interrogation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterrogationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterrogationRequest) ProtoMessage() {}

func (x *InterrogationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interrogation_interrogation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterrogationRequest.ProtoReflect.Descriptor instead.
func (*InterrogationRequest) Descriptor() ([]byte, []int) {
	return file_interrogation_interrogation_proto_rawDescGZIP(), []int{2}
}

func (x *InterrogationRequest) GetSuspectId() string {
	if x != nil {
		return x.SuspectId
	}
	return ""
}

func (x *InterrogationRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

type SuspectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *SuspectResponse) Reset() {
	*x = SuspectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interrogation_interrogation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuspectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspectResponse) ProtoMessage() {}

func (x *SuspectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interrogation_interrogation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspectResponse.ProtoReflect.Descriptor instead.
func (*SuspectResponse) Descriptor() ([]byte, []int) {
	return file_interrogation_interrogation_proto_rawDescGZIP(), []int{3}
}

func (x *SuspectResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_interrogation_interrogation_proto protoreflect.FileDescriptor

var file_interrogation_interrogation_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x70, 0x62, 0x22, 0x31, 0x0a, 0x0e, 0x57, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x10, 0x57, 0x69, 0x74, 0x6e, 0x65,
	0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x56, 0x0a, 0x14, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x22, 0x2d, 0x0a, 0x0f, 0x53, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0xd4, 0x01, 0x0a, 0x14, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5b, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x57, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x1f, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x70, 0x62, 0x2e, 0x57, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x70, 0x62, 0x2e, 0x57, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x12, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x72,
	0x6f, 0x67, 0x61, 0x74, 0x65, 0x53, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x12, 0x25, 0x2e, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x53, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x6f, 0x64, 0x61, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f,
	0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x3b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_interrogation_interrogation_proto_rawDescOnce sync.Once
	file_interrogation_interrogation_proto_rawDescData = file_interrogation_interrogation_proto_rawDesc
)

func file_interrogation_interrogation_proto_rawDescGZIP() []byte {
	file_interrogation_interrogation_proto_rawDescOnce.Do(func() {
		file_interrogation_interrogation_proto_rawDescData = protoimpl.X.CompressGZIP(file_interrogation_interrogation_proto_rawDescData)
	})
	return file_interrogation_interrogation_proto_rawDescData
}

var file_interrogation_interrogation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_interrogation_interrogation_proto_goTypes = []any{
	(*WitnessRequest)(nil),       // 0: interrogationpb.WitnessRequest
	(*WitnessStatement)(nil),     // 1: interrogationpb.WitnessStatement
	(*InterrogationRequest)(nil), // 2: interrogationpb.InterrogationRequest
	(*SuspectResponse)(nil),      // 3: interrogationpb.SuspectResponse
}
var file_interrogation_interrogation_proto_depIdxs = []int32{
	0, // 0: interrogationpb.InterrogationService.GetWitnessStatement:input_type -> interrogationpb.WitnessRequest
	2, // 1: interrogationpb.InterrogationService.InterrogateSuspect:input_type -> interrogationpb.InterrogationRequest
	1, // 2: interrogationpb.InterrogationService.GetWitnessStatement:output_type -> interrogationpb.WitnessStatement
	3, // 3: interrogationpb.InterrogationService.InterrogateSuspect:output_type -> interrogationpb.SuspectResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_interrogation_interrogation_proto_init() }
func file_interrogation_interrogation_proto_init() {
	if File_interrogation_interrogation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_interrogation_interrogation_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*WitnessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interrogation_interrogation_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*WitnessStatement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interrogation_interrogation_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*InterrogationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interrogation_interrogation_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SuspectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_interrogation_interrogation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interrogation_interrogation_proto_goTypes,
		DependencyIndexes: file_interrogation_interrogation_proto_depIdxs,
		MessageInfos:      file_interrogation_interrogation_proto_msgTypes,
	}.Build()
	File_interrogation_interrogation_proto = out.File
	file_interrogation_interrogation_proto_rawDesc = nil
	file_interrogation_interrogation_proto_goTypes = nil
	file_interrogation_interrogation_proto_depIdxs = nil
}
