// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: interrogation/interrogation.proto

package interrogationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Suspect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CaseId      string `protobuf:"bytes,2,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Suspect) Reset() {
	*x = Suspect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interrogation_interrogation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Suspect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suspect) ProtoMessage() {}

func (x *Suspect) ProtoReflect() protoreflect.Message {
	mi := &file_interrogation_interrogation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suspect.ProtoReflect.Descriptor instead.
func (*Suspect) Descriptor() ([]byte, []int) {
	return file_interrogation_interrogation_proto_rawDescGZIP(), []int{0}
}

func (x *Suspect) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Suspect) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *Suspect) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Suspect) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListSuspectsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaseId string `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
}

func (x *ListSuspectsRequest) Reset() {
	*x = ListSuspectsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interrogation_interrogation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSuspectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSuspectsRequest) ProtoMessage() {}

func (x *ListSuspectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interrogation_interrogation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSuspectsRequest.ProtoReflect.Descriptor instead.
func (*ListSuspectsRequest) Descriptor() ([]byte, []int) {
	return file_interrogation_interrogation_proto_rawDescGZIP(), []int{1}
}

func (x *ListSuspectsRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

type SuspectList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Suspects []*Suspect `protobuf:"bytes,1,rep,name=suspects,proto3" json:"suspects,omitempty"`
}

func (x *SuspectList) Reset() {
	*x = SuspectList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interrogation_interrogation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuspectList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspectList) ProtoMessage() {}

func (x *SuspectList) ProtoReflect() protoreflect.Message {
	mi := &file_interrogation_interrogation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspectList.ProtoReflect.Descriptor instead.
func (*SuspectList) Descriptor() ([]byte, []int) {
	return file_interrogation_interrogation_proto_rawDescGZIP(), []int{2}
}

func (x *SuspectList) GetSuspects() []*Suspect {
	if x != nil {
		return x.Suspects
	}
	return nil
}

type InterrogationQuestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SuspectId string `protobuf:"bytes,2,opt,name=suspect_id,json=suspectId,proto3" json:"suspect_id,omitempty"`
	Question  string `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Answer    string `protobuf:"bytes,4,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *InterrogationQuestion) Reset() {
	*x = InterrogationQuestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interrogation_interrogation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterrogationQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterrogationQuestion) ProtoMessage() {}

func (x *InterrogationQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_interrogation_interrogation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterrogationQuestion.ProtoReflect.Descriptor instead.
func (*InterrogationQuestion) Descriptor() ([]byte, []int) {
	return file_interrogation_interrogation_proto_rawDescGZIP(), []int{3}
}

func (x *InterrogationQuestion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InterrogationQuestion) GetSuspectId() string {
	if x != nil {
		return x.SuspectId
	}
	return ""
}

func (x *InterrogationQuestion) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *InterrogationQuestion) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type GetInterrogationQuestionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuspectId string `protobuf:"bytes,1,opt,name=suspect_id,json=suspectId,proto3" json:"suspect_id,omitempty"`
}

func (x *GetInterrogationQuestionsRequest) Reset() {
	*x = GetInterrogationQuestionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interrogation_interrogation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInterrogationQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterrogationQuestionsRequest) ProtoMessage() {}

func (x *GetInterrogationQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interrogation_interrogation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterrogationQuestionsRequest.ProtoReflect.Descriptor instead.
func (*GetInterrogationQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_interrogation_interrogation_proto_rawDescGZIP(), []int{4}
}

func (x *GetInterrogationQuestionsRequest) GetSuspectId() string {
	if x != nil {
		return x.SuspectId
	}
	return ""
}

type InterrogationQuestionList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Questions []*InterrogationQuestion `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
}

func (x *InterrogationQuestionList) Reset() {
	*x = InterrogationQuestionList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interrogation_interrogation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterrogationQuestionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterrogationQuestionList) ProtoMessage() {}

func (x *InterrogationQuestionList) ProtoReflect() protoreflect.Message {
	mi := &file_interrogation_interrogation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterrogationQuestionList.ProtoReflect.Descriptor instead.
func (*InterrogationQuestionList) Descriptor() ([]byte, []int) {
	return file_interrogation_interrogation_proto_rawDescGZIP(), []int{5}
}

func (x *InterrogationQuestionList) GetQuestions() []*InterrogationQuestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

var File_interrogation_interrogation_proto protoreflect.FileDescriptor

var file_interrogation_interrogation_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x70, 0x62, 0x22, 0x68, 0x0a, 0x07, 0x53, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e,
	0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x73, 0x65, 0x49, 0x64, 0x22, 0x43,
	0x0a, 0x0b, 0x53, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x34, 0x0a,
	0x08, 0x73, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70,
	0x62, 0x2e, 0x53, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x52, 0x08, 0x73, 0x75, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x73, 0x22, 0x7a, 0x0a, 0x15, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22,
	0x41, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74,
	0x49, 0x64, 0x22, 0x61, 0x0a, 0x19, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x44, 0x0a, 0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0xe6, 0x01, 0x0a, 0x14, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x72,
	0x6f, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52,
	0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x73, 0x12, 0x24,
	0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x53, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x7a, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f,
	0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x31, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x2d,
	0x5a, 0x2b, 0x6f, 0x64, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x3b, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x72, 0x6f, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_interrogation_interrogation_proto_rawDescOnce sync.Once
	file_interrogation_interrogation_proto_rawDescData = file_interrogation_interrogation_proto_rawDesc
)

func file_interrogation_interrogation_proto_rawDescGZIP() []byte {
	file_interrogation_interrogation_proto_rawDescOnce.Do(func() {
		file_interrogation_interrogation_proto_rawDescData = protoimpl.X.CompressGZIP(file_interrogation_interrogation_proto_rawDescData)
	})
	return file_interrogation_interrogation_proto_rawDescData
}

var file_interrogation_interrogation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_interrogation_interrogation_proto_goTypes = []any{
	(*Suspect)(nil),                          // 0: interrogationpb.Suspect
	(*ListSuspectsRequest)(nil),              // 1: interrogationpb.ListSuspectsRequest
	(*SuspectList)(nil),                      // 2: interrogationpb.SuspectList
	(*InterrogationQuestion)(nil),            // 3: interrogationpb.InterrogationQuestion
	(*GetInterrogationQuestionsRequest)(nil), // 4: interrogationpb.GetInterrogationQuestionsRequest
	(*InterrogationQuestionList)(nil),        // 5: interrogationpb.InterrogationQuestionList
}
var file_interrogation_interrogation_proto_depIdxs = []int32{
	0, // 0: interrogationpb.SuspectList.suspects:type_name -> interrogationpb.Suspect
	3, // 1: interrogationpb.InterrogationQuestionList.questions:type_name -> interrogationpb.InterrogationQuestion
	1, // 2: interrogationpb.InterrogationService.ListSuspects:input_type -> interrogationpb.ListSuspectsRequest
	4, // 3: interrogationpb.InterrogationService.GetInterrogationQuestions:input_type -> interrogationpb.GetInterrogationQuestionsRequest
	2, // 4: interrogationpb.InterrogationService.ListSuspects:output_type -> interrogationpb.SuspectList
	5, // 5: interrogationpb.InterrogationService.GetInterrogationQuestions:output_type -> interrogationpb.InterrogationQuestionList
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_interrogation_interrogation_proto_init() }
func file_interrogation_interrogation_proto_init() {
	if File_interrogation_interrogation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_interrogation_interrogation_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Suspect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interrogation_interrogation_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListSuspectsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interrogation_interrogation_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SuspectList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interrogation_interrogation_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*InterrogationQuestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interrogation_interrogation_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetInterrogationQuestionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interrogation_interrogation_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*InterrogationQuestionList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_interrogation_interrogation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interrogation_interrogation_proto_goTypes,
		DependencyIndexes: file_interrogation_interrogation_proto_depIdxs,
		MessageInfos:      file_interrogation_interrogation_proto_msgTypes,
	}.Build()
	File_interrogation_interrogation_proto = out.File
	file_interrogation_interrogation_proto_rawDesc = nil
	file_interrogation_interrogation_proto_goTypes = nil
	file_interrogation_interrogation_proto_depIdxs = nil
}
